import Head from "next/head";
import styles from "../styles/Home.module.css";
import { SendSOLToRandomAddress, SolanaWallet } from "../components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next JS + Next UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* code here */}
      <div>
        <div>
          <SolanaWallet />
        </div>
        <div
          style={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            paddingTop: "20%",
            paddingBottom: "20%" 
          }}
        >
          <SendSOLToRandomAddress />
        </div>
      </div>
    </div>
  );
}
